#!/usr/bin/env bash

flavor=$(cat /sandbox-flavor)
if [ "$flavor" == "hdf" ]; then
 name="sandbox-hdf-standalone-cda-ready"
 hostname="sandbox-hdf.hortonworks.com"
elif [ "$flavor" == "hdp" ]; then
 name="sandbox-hdp-security"
 hostname="sandbox-hdp.hortonworks.com"
fi

version=$(docker images | grep $name  | awk '{print $2}');
image="hortonworks/$name:$version";

# Create cda docker network
docker network create cda

# Deploy the sandbox into the cda docker network
docker run --privileged --name $name -h $hostname --network=cda --network-alias=$hostname -d $image

# Deploy the proxy container.  This script was generated by running
/sandbox/proxy/generate-proxy-deploy-script.sh
/sandbox/proxy/proxy-deploy.sh
